### PR TITLE
Multiple keys in 1 generator

### PR DESCRIPTION
**Pull request by andrefs**
I added support for generating multiple distinct IDs using one generator. This saves you the trouble of having to open one generator in a distinct port for each type of ID you want to be generating.

Basically you can pass a **key** parameter to `Generator.generate()` or to `Accessor.next()`, to generate an ID for that key. There's a new method, `Generator.add(key, options)` which adds a new key to the generator.

Internally, everything is kept in a `keys` object; all `options` are relative to each key, except for **port**.

No API breaks: all previous methods can still be used because a **'__default'** key is always added to the Generator (when it is initialized) which is used when the **key** parameter is omitted.

I updated the docs and tests, let me know if there's anything else I can do in order to have this merged.

### CODE REVIEW

**Comment by GochoMugo** [comment]
Thanks a lot for the PR. We wonder how we lived without this feature. It is by all means a merge candidate.

But before we merge it, just one little query. What if the key does not exist? We should consider that and most certainly add a test for such a case.

Please fix that and we could merge it asap. Thanks @andrefs

**Comment by andrefs** [comment]
Hi @GochoMugo , thank you for your quick reply.

That's a good question. In my opinion, requesting an ID for a key which doesn't exist should return a `null`. Alternatively, the key could be added on-the-fly to the generator (with default options) and the first ID returned.

I think the best approach would be to have an optional `autoAddKeys` parameter in the `options` object in the `Generator()` initialization. The default would be `false`. When set to `true`, calling `generator.generate(key)` with an unexistent key would first create it (using the default options) and then return its first ID.

Let me know if you agree with this solution, and I will implement it and update the docs and tests.

I just thought of another issue: what if you call a `generator.add(key)` with an already added key? I would say this should be ignored and nothing would happen. What do you think?

**Comment by GochoMugo** [comment]
Wow. That's insightful.
1. `generator#add` may return `true` for successful key additions. Otherwise `false`. So when an already-added key is tried to be added, it just returns `false`.
2. The `autoAddKeys` option is on-point. If it is set to `true`, using a non-existent key should have it added and a new ID returned or passed to the callback. If set to `false`, using a non-existent key should return `null` in the case of `generator#generate()` or pass an `Error` to the callback in the case of `accessor#next()`

For the time being before we devise a method of creating errors and appropriate error codes, feel free to use `new Error("some message")`. (If you think of a way to do this, please create another issue for it)

Ooh and don't forget about docs and tests. ;)

What do you think? Hack On @andrefs

**Comment by GochoMugo** [comment]
Sorry closed the issue by mistake. Big Thumbs, Small Icons on a Touch Screen. My Bad!

**Comment by andrefs** [comment]
@GochoMugo that sounds about right. I already updated the code, docs and tests.
Let me know if you find anything wrong or missing.

**Pull request merged**
